### PR TITLE
Update windows.xml

### PR DESCRIPTION
**Pull request by Sindin-Luckstone**
Changes to fix bug preventing use of advanced generation.

### CODE REVIEW

**Comment by Sindin-Luckstone** [comment]
Fixed the ability to make new worlds, but investigating further issue of crash on world creation.

**Comment by War3zuk** [comment]
Its always crashed when previewing.. well it has for me & many others from 2 alphas ago...

**Comment by Sindin-Luckstone** [comment]
I fixed the crash i was talking about (it did not like the pine vs burnt forest coloration so i removed them) i have managed to get it to make me a world in 4k and am now working on a 15k world gen with this new file.

**Comment by Sindin-Luckstone** [comment]
Please note i am doing this on a monster of a pc and its hitting my 128gb of ram(ram/swap) hard for this so i do not think this is a feasible generation for just anyone.

**Comment by War3zuk** [comment]
cool send me the fixed file once tested & ill take a look at the changes...

**Comment by Sindin-Luckstone** [comment]
I have determined it to be a ram issue. Loading the image preview uses a lot of ram, like we are talking tens of GB depending on the size. A simple 15k world with the settings below would not load a preview on my system with 32gb of base ram and another 128gb dedicated m.2 nvme swap file. meaning 15k worlds will need to be externally generated if you want a preview(some truely monstrous machine would need to generate it). I am running it on smaller world sizes to see what the limits and restrictions currently are and there respective ram/swap usage. Current settings are in the image below. 4k worlds at the very least are good and if this works out all base game world sizes should be doable.
image

**Comment by War3zuk** [comment]
Its probably why mine has failed for the past year as I normally Gen 8k 12k & 16k with preview as thats mostly played by players..thanks for the adjustments on the original file you posted..

**Comment by Sindin-Luckstone** [comment]
I seem to have gotten it to make maps up to 8k with 32 GB of ram, for some reason the rendering phase refuses to use the swap file. i attempted to give it 256 GB of swap file space but it was still using less then 5 GB on system monitor.
image
system monitor showed it was using 28gb of ram for the final render of the 8k map with max towns and highest preview.

**Pull request closed without merging**
